<a href="https://colab.research.google.com/github/KiranPortfolio1/Airbnb/blob/main/Saikiran_Subbagari_Week_1_Project_coursename.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
!pip install numpy pandas streamlit gdown currencyconverter

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [53]:
import numpy as np

# For readability purposes, we will disable scientific notation for numbers
np.set_printoptions(suppress=True)

In [54]:
import os
import shutil
import gdown
from numpy import genfromtxt
# Download file from Google Drive
# This file is based on data from: http://insideairbnb.com/get-the-data/
file_id_1 = "13fyESiH1ZEnMV6eabAyhe20t4W6peEWK"
downloaded_file_1 = "WK1_Airbnb_Amsterdam_listings_proj.csv"

# Download the file from Google Drive
gdown.download(id=file_id_1, output=downloaded_file_1)

Downloading...
From: https://drive.google.com/uc?id=13fyESiH1ZEnMV6eabAyhe20t4W6peEWK
To: /content/WK1_Airbnb_Amsterdam_listings_proj.csv
100%|██████████| 246k/246k [00:00<00:00, 67.2MB/s]


'WK1_Airbnb_Amsterdam_listings_proj.csv'

In [55]:
my_data = genfromtxt(downloaded_file_1, delimiter="|", skip_header=False, dtype="unicode")

In [56]:
print(my_data)

[['' '0' '1' ... '6170' '6171' '6172']
 ['id' '23726706' '35815036' ... '35760705' '36900951' '40575103']
 ['price' '$88.00' '$105.00' ... '$180.00' '$174.00' '$65.00']
 ['latitude' '52.34916' '52.42419' ... '52.42624' '52.31983' '52.33946']
 ['longitude' '4.97879' '4.95689' ... '4.90236' '4.86463' '4.95749']]


In [57]:
print(my_data[:,0:4])

[['' '0' '1' '2']
 ['id' '23726706' '35815036' '31553121']
 ['price' '$88.00' '$105.00' '$152.00']
 ['latitude' '52.34916' '52.42419' '52.43237']
 ['longitude' '4.97879' '4.95689' '4.91821']]


In [58]:
print(my_data[1:, :])

[['id' '23726706' '35815036' ... '35760705' '36900951' '40575103']
 ['price' '$88.00' '$105.00' ... '$180.00' '$174.00' '$65.00']
 ['latitude' '52.34916' '52.42419' ... '52.42624' '52.31983' '52.33946']
 ['longitude' '4.97879' '4.95689' ... '4.90236' '4.86463' '4.95749']]


In [59]:
my_data=my_data[1:, :]

In [60]:
print(my_data)

[['id' '23726706' '35815036' ... '35760705' '36900951' '40575103']
 ['price' '$88.00' '$105.00' ... '$180.00' '$174.00' '$65.00']
 ['latitude' '52.34916' '52.42419' ... '52.42624' '52.31983' '52.33946']
 ['longitude' '4.97879' '4.95689' ... '4.90236' '4.86463' '4.95749']]


In [61]:
matrix=my_data[:, 1:]

In [62]:
print(matrix)

[['23726706' '35815036' '31553121' ... '35760705' '36900951' '40575103']
 ['$88.00' '$105.00' '$152.00' ... '$180.00' '$174.00' '$65.00']
 ['52.34916' '52.42419' '52.43237' ... '52.42624' '52.31983' '52.33946']
 ['4.97879' '4.95689' '4.91821' ... '4.90236' '4.86463' '4.95749']]


In [63]:
matrix=np.transpose(matrix)

In [64]:
print(matrix[0:5])

[['23726706' '$88.00' '52.34916' '4.97879']
 ['35815036' '$105.00' '52.42419' '4.95689']
 ['31553121' '$152.00' '52.43237' '4.91821']
 ['34745823' '$87.00' '52.2962' '5.01231']
 ['44586947' '$160.00' '52.31475' '5.0303']]


In [65]:
matrix=np.char.replace(matrix,"$","")
print(matrix[0:5])

[['23726706' '88.00' '52.34916' '4.97879']
 ['35815036' '105.00' '52.42419' '4.95689']
 ['31553121' '152.00' '52.43237' '4.91821']
 ['34745823' '87.00' '52.2962' '5.01231']
 ['44586947' '160.00' '52.31475' '5.0303']]


In [66]:
matrix=np.char.replace(matrix,",","")
print(matrix[0:5])

[['23726706' '88.00' '52.34916' '4.97879']
 ['35815036' '105.00' '52.42419' '4.95689']
 ['31553121' '152.00' '52.43237' '4.91821']
 ['34745823' '87.00' '52.2962' '5.01231']
 ['44586947' '160.00' '52.31475' '5.0303']]


In [67]:
matrix[(np.char.find(matrix,"$")> -1)]

array([], dtype='<U18')

In [68]:
matrix[(np.char.find(matrix,",") > -1)]

array([], dtype='<U18')

In [69]:
matrix=matrix.astype(np.float32)

In [70]:
print(matrix[0:5])

[[23726706.            88.            52.34916        4.97879]
 [35815036.           105.            52.42419        4.95689]
 [31553120.           152.            52.43237        4.91821]
 [34745824.            87.            52.2962         5.01231]
 [44586948.           160.            52.31475        5.0303 ]]


In [71]:
from currency_converter import CurrencyConverter
cc = CurrencyConverter()
british_pound = cc.convert(1,"USD","GBP")
print(matrix[:,1])

[ 88. 105. 152. ... 180. 174.  65.]


In [72]:
gbp_rate=cc.convert(1,"USD","GBP")
matrix[:,1]=matrix[:,1] * gbp_rate

In [73]:
print(matrix[:,1])

[ 72.26188   86.221565 124.81598  ... 147.8084   142.88145   53.375256]


In [74]:
matrix[:,1] = matrix[:,1] * 1.07

In [75]:
print(matrix[:,1])

[ 77.32021   92.25708  133.5531   ... 158.15498  152.88316   57.111526]


In [76]:
matrix[:,1] = np.round(matrix[:,1], 2)
print(matrix[:,1])

[ 77.32  92.26 133.55 ... 158.15 152.88  57.11]


In [77]:
print(matrix[:,1])

[ 77.32  92.26 133.55 ... 158.15 152.88  57.11]


In [78]:
latitude = 52.3752
longitude = 4.8840 

In [79]:
def from_location_to_airbnb_listing_in_meters(
    lat1: float, lon1: float, lat2: np.ndarray, lon2: np.ndarray
):
    R = 6371000  # radius of Earth in meters
    phi_1 = np.radians(lat1)
    phi_2 = np.radians(lat2)

    delta_phi = np.radians(lat2 - lat1)
    delta_lambda = np.radians(lon2 - lon1)

    a = (
        np.sin(delta_phi / 2.0) ** 2
        + np.cos(phi_1) * np.cos(phi_2) * np.sin(delta_lambda / 2.0) ** 2
    )

    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a))

    meters = R * c  # output distance in meters

    return np.round(meters, 0)

In [80]:
conv_to_meters = np.vectorize(from_location_to_airbnb_listing_in_meters)

In [81]:
conv_to_meters(latitude, longitude, matrix[:, 2], matrix[:, 3])

array([7058., 7357., 6767., ..., 5810., 6296., 6380.])

In [82]:
# Run the previous method
latitude = 52.3752
longitude = 4.8840 
meters = from_location_to_airbnb_listing_in_meters (
    latitude, longitude, matrix[:, 2], matrix[:, 3]
)

# Add an axis to make concatenation possible
meters = meters.reshape(-1, 1)

# Append the distance in meters to the matrix
matrix = np.concatenate((matrix, meters), axis=1)

In [83]:
# Append a color to the matrix
colors = np.zeros(meters.shape)
matrix = np.concatenate((matrix, colors), axis=1)

# Append our entry to the matrix
fav_entry = np.array([1, 0, 52.3600, 4.8852, 0, 1]).reshape(1, -1) # Change coordinates to your favorite location
matrix = np.concatenate((fav_entry, matrix), axis=0)

# Entries: airbnb_id, price, latitude, longitude,
# meters from favorite point, color
matrix[:5, :]

array([[       1.        ,        0.        ,       52.36      ,
               4.8852    ,        0.        ,        1.        ],
       [23726706.        ,       77.31999969,       52.34915924,
               4.97878981,     7058.        ,        0.        ],
       [35815036.        ,       92.26000214,       52.42419052,
               4.95689011,     7358.        ,        0.        ],
       [31553120.        ,      133.55000305,       52.43236923,
               4.91821003,     6767.        ,        0.        ],
       [34745824.        ,       76.44000244,       52.2961998 ,
               5.01231003,    12376.        ,        0.        ]])

In [84]:
# Export the data to use in the primer for next week
np.savetxt("WK1_Airbnb_Amsterdam_listings_proj_solution.csv", matrix, delimiter=",")

In [85]:
from google.colab import files

# Download the file locally
files.download('WK1_Airbnb_Amsterdam_listings_proj_solution.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [86]:
%%writefile streamlit_app.py
import pandas as pd
import plotly.express as px
import streamlit as st

# Display title and text
st.title("Week 1 - Data and visualization")
st.markdown("Here we can see the dataframe created during this weeks project.")

# Read dataframe
dataframe = pd.read_csv(
    "WK1_Airbnb_Amsterdam_listings_proj_solution.csv",
    names=[
        "Airbnb Listing ID",
        "Price",
        "Latitude",
        "Longitude",
        "Meters from chosen location",
        "Location",
    ],
)

# We have a limited budget, therefore we would like to exclude
# listings with a price above 100 pounds per night
dataframe = dataframe[dataframe["Price"] <= 100]

# Display as integer
dataframe["Airbnb Listing ID"] = dataframe["Airbnb Listing ID"].astype(int)
# Round of values
dataframe["Price"] = "£ " + dataframe["Price"].round(2).astype(str) # <--- CHANGE THIS POUND SYMBOL IF YOU CHOSE CURRENCY OTHER THAN POUND
# Rename the number to a string
dataframe["Location"] = dataframe["Location"].replace(
    {1.0: "To visit", 0.0: "Airbnb listing"}
)

# Display dataframe and text
st.dataframe(dataframe)
st.markdown("Below is a map showing all the Airbnb listings with a red dot and the location we've chosen with a blue dot.")

# Create the plotly express figure
fig = px.scatter_mapbox(
    dataframe,
    lat="Latitude",
    lon="Longitude",
    color="Location",
    zoom=11,
    height=500,
    width=800,
    hover_name="Price",
    hover_data=["Meters from chosen location", "Location"],
    labels={"color": "Locations"},
)
fig.update_geos(center=dict(lat=dataframe.iloc[0][2], lon=dataframe.iloc[0][3]))
fig.update_layout(mapbox_style="stamen-terrain")

# Show the figure
st.plotly_chart(fig, use_container_width=True)

Overwriting streamlit_app.py


In [87]:
from google.colab import files

# Download the file locally
files.download('streamlit_app.py')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [88]:
%%writefile requirements.txt
pandas
streamlit
plotly

Overwriting requirements.txt


In [89]:
from google.colab import files

# Download the file locally
files.download('requirements.txt')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>