<a href="https://colab.research.google.com/github/KiranPortfolio1/Airbnb/blob/main/Saikiran%20Subbagari%20-%20Week%201%20Project%20-coursename.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy pandas streamlit gdown currencyconverter

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 40.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 563.6/563.6 KB 14.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 184.3/184.3 KB 9.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.1/82.1 KB 1.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 164.8/164.8 KB 1.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 28.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 238.7/238.7 KB 3.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 KB 2.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 11.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.5/84.5 KB 2.4 MB/s eta 0:00:00
  Created wheel for validators: filename=validators-0.20.0-

In [2]:
import numpy as np

# For readability purposes, we will disable scientific notation for numbers
np.set_printoptions(suppress=True)

In [3]:
import os
import shutil
import gdown
from numpy import genfromtxt
# Download file from Google Drive
# This file is based on data from: http://insideairbnb.com/get-the-data/
file_id_1 = "13fyESiH1ZEnMV6eabAyhe20t4W6peEWK"
downloaded_file_1 = "WK1_Airbnb_Amsterdam_listings_proj.csv"

# Download the file from Google Drive
gdown.download(id=file_id_1, output=downloaded_file_1)

Downloading...
From: https://drive.google.com/uc?id=13fyESiH1ZEnMV6eabAyhe20t4W6peEWK
To: /content/WK1_Airbnb_Amsterdam_listings_proj.csv
100%|██████████| 246k/246k [00:00<00:00, 57.0MB/s]


'WK1_Airbnb_Amsterdam_listings_proj.csv'

In [4]:
my_data = genfromtxt(downloaded_file_1, delimiter="|", skip_header=False, dtype="unicode")

In [5]:
print(my_data)

[['' '0' '1' ... '6170' '6171' '6172']
 ['id' '23726706' '35815036' ... '35760705' '36900951' '40575103']
 ['price' '$88.00' '$105.00' ... '$180.00' '$174.00' '$65.00']
 ['latitude' '52.34916' '52.42419' ... '52.42624' '52.31983' '52.33946']
 ['longitude' '4.97879' '4.95689' ... '4.90236' '4.86463' '4.95749']]


In [6]:
print(my_data[:,0:4])

[['' '0' '1' '2']
 ['id' '23726706' '35815036' '31553121']
 ['price' '$88.00' '$105.00' '$152.00']
 ['latitude' '52.34916' '52.42419' '52.43237']
 ['longitude' '4.97879' '4.95689' '4.91821']]


In [7]:
print(my_data[1:, :])

[['id' '23726706' '35815036' ... '35760705' '36900951' '40575103']
 ['price' '$88.00' '$105.00' ... '$180.00' '$174.00' '$65.00']
 ['latitude' '52.34916' '52.42419' ... '52.42624' '52.31983' '52.33946']
 ['longitude' '4.97879' '4.95689' ... '4.90236' '4.86463' '4.95749']]


In [8]:
my_data=my_data[1:, :]

In [9]:
print(my_data)

[['id' '23726706' '35815036' ... '35760705' '36900951' '40575103']
 ['price' '$88.00' '$105.00' ... '$180.00' '$174.00' '$65.00']
 ['latitude' '52.34916' '52.42419' ... '52.42624' '52.31983' '52.33946']
 ['longitude' '4.97879' '4.95689' ... '4.90236' '4.86463' '4.95749']]


In [10]:
matrix=my_data[:, 1:]

In [11]:
print(matrix)

[['23726706' '35815036' '31553121' ... '35760705' '36900951' '40575103']
 ['$88.00' '$105.00' '$152.00' ... '$180.00' '$174.00' '$65.00']
 ['52.34916' '52.42419' '52.43237' ... '52.42624' '52.31983' '52.33946']
 ['4.97879' '4.95689' '4.91821' ... '4.90236' '4.86463' '4.95749']]


In [12]:
matrix=np.transpose(matrix)

In [13]:
print(matrix[0:5])

[['23726706' '$88.00' '52.34916' '4.97879']
 ['35815036' '$105.00' '52.42419' '4.95689']
 ['31553121' '$152.00' '52.43237' '4.91821']
 ['34745823' '$87.00' '52.2962' '5.01231']
 ['44586947' '$160.00' '52.31475' '5.0303']]


In [14]:
matrix=np.char.replace(matrix,"$","")
print(matrix[0:5])

[['23726706' '88.00' '52.34916' '4.97879']
 ['35815036' '105.00' '52.42419' '4.95689']
 ['31553121' '152.00' '52.43237' '4.91821']
 ['34745823' '87.00' '52.2962' '5.01231']
 ['44586947' '160.00' '52.31475' '5.0303']]


In [15]:
matrix=np.char.replace(matrix,",","")
print(matrix[0:5])

[['23726706' '88.00' '52.34916' '4.97879']
 ['35815036' '105.00' '52.42419' '4.95689']
 ['31553121' '152.00' '52.43237' '4.91821']
 ['34745823' '87.00' '52.2962' '5.01231']
 ['44586947' '160.00' '52.31475' '5.0303']]


In [16]:
matrix[(np.char.find(matrix,"$")> -1)]

array([], dtype='<U18')

In [17]:
matrix[(np.char.find(matrix,",") > -1)]

array([], dtype='<U18')

In [18]:
matrix=matrix.astype(np.float32)

In [19]:
print(matrix[0:5])

[[23726706.            88.            52.34916        4.97879]
 [35815036.           105.            52.42419        4.95689]
 [31553120.           152.            52.43237        4.91821]
 [34745824.            87.            52.2962         5.01231]
 [44586948.           160.            52.31475        5.0303 ]]


In [20]:
from currency_converter import CurrencyConverter
cc = CurrencyConverter()
indian_rupee = cc.convert(1,"USD","INR")
print(matrix[:,1])

[ 88. 105. 152. ... 180. 174.  65.]


In [21]:
inr_rate=cc.convert(1,"USD","INR")
matrix[:,1]=matrix[:,1] * inr_rate

In [22]:
print(matrix[:,1])

[ 7168.8994  8553.801  12382.645  ... 14663.658  14174.869   5295.21  ]


In [23]:
matrix[:,1] = matrix[:,1] * 1.07

In [24]:
print(matrix[:,1])

[ 7670.7227  9152.567  13249.431  ... 15690.115  15167.11    5665.875 ]


In [25]:
matrix[:,1] = np.round(matrix[:,1], 2)
print(matrix[:,1])

[ 7670.72  9152.57 13249.43 ... 15690.12 15167.11  5665.88]


In [26]:
print(matrix[:,1])

[ 7670.72  9152.57 13249.43 ... 15690.12 15167.11  5665.88]


In [27]:
latitude = 52.3752
longitude = 4.8840 

In [41]:
def from_location_to_airbnb_listing_in_meters(
    lat1: float, lon1: float, lat2: np.ndarray, lon2: np.ndarray
):
    R = 6371000  # radius of Earth in meters
    phi_1 = np.radians(lat1)
    phi_2 = np.radians(lat2)

    delta_phi = np.radians(lat2 - lat1)
    delta_lambda = np.radians(lon2 - lon1)

    a = (
        np.sin(delta_phi / 2.0) ** 2
        + np.cos(phi_1) * np.cos(phi_2) * np.sin(delta_lambda / 2.0) ** 2
    )

    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a))

    meters = R * c  # output distance in meters

    return np.round(meters, 0)

In [34]:
conv_to_meters = np.vectorize(from_location_to_airbnb_listing_in_meters)

In [35]:
conv_to_meters(latitude, longitude, matrix[:, 2], matrix[:, 3])

array([7058., 7357., 6767., ..., 5810., 6296., 6380.])

In [42]:
# Run the previous method
latitude = 52.3752
longitude = 4.8840 
meters = from_location_to_airbnb_listing_in_meters (
    latitude, longitude, matrix[:, 2], matrix[:, 3]
)

# Add an axis to make concatenation possible
meters = meters.reshape(-1, 1)

# Append the distance in meters to the matrix
matrix = np.concatenate((matrix, meters), axis=1)

In [43]:
# Append a color to the matrix
colors = np.zeros(meters.shape)
matrix = np.concatenate((matrix, colors), axis=1)

# Append our entry to the matrix
fav_entry = np.array([1, 0, 52.3600, 4.8852, 0, 1]).reshape(1, -1) # Change coordinates to your favorite location
matrix = np.concatenate((fav_entry, matrix), axis=0)

# Entries: airbnb_id, price, latitude, longitude,
# meters from favorite point, color
matrix[:5, :]

array([[       1.        ,        0.        ,       52.36      ,
               4.8852    ,        0.        ,        1.        ],
       [23726706.        ,     7670.72021484,       52.34915924,
               4.97878981,     7058.        ,        0.        ],
       [35815036.        ,     9152.5703125 ,       52.42419052,
               4.95689011,     7358.        ,        0.        ],
       [31553120.        ,    13249.4296875 ,       52.43236923,
               4.91821003,     6767.        ,        0.        ],
       [34745824.        ,     7583.56005859,       52.2961998 ,
               5.01231003,    12376.        ,        0.        ]])

In [44]:
# Export the data to use in the primer for next week
np.savetxt("WK1_Airbnb_Amsterdam_listings_proj_solution.csv", matrix, delimiter=",")

In [45]:
from google.colab import files

# Download the file locally
files.download('WK1_Airbnb_Amsterdam_listings_proj_solution.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [48]:
%%writefile streamlit_app.py
import pandas as pd
import plotly.express as px
import streamlit as st

# Display title and text
st.title("Week 1 - Data and visualization")
st.markdown("Here we can see the dataframe created during this weeks project.")

# Read dataframe
dataframe = pd.read_csv(
    "WK1_Airbnb_Amsterdam_listings_proj_solution.csv",
    names=[
        "Airbnb Listing ID",
        "Price",
        "Latitude",
        "Longitude",
        "Meters from chosen location",
        "Location",
    ],
)

# We have a limited budget, therefore we would like to exclude
# listings with a price above 100 pounds per night
dataframe = dataframe[dataframe["Price"] <= 100]

# Display as integer
dataframe["Airbnb Listing ID"] = dataframe["Airbnb Listing ID"].astype(int)
# Round of values
dataframe["Price"] = "₹ " + dataframe["Price"].round(2).astype(str) # <--- CHANGE THIS POUND SYMBOL IF YOU CHOSE CURRENCY OTHER THAN POUND
# Rename the number to a string
dataframe["Location"] = dataframe["Location"].replace(
    {1.0: "To visit", 0.0: "Airbnb listing"}
)

# Display dataframe and text
st.dataframe(dataframe)
st.markdown("Below is a map showing all the Airbnb listings with a red dot and the location we've chosen with a blue dot.")

# Create the plotly express figure
fig = px.scatter_mapbox(
    dataframe,
    lat="Latitude",
    lon="Longitude",
    color="Location",
    zoom=11,
    height=500,
    width=800,
    hover_name="Price",
    hover_data=["Meters from chosen location", "Location"],
    labels={"color": "Locations"},
)
fig.update_geos(center=dict(lat=dataframe.iloc[0][2], lon=dataframe.iloc[0][3]))
fig.update_layout(mapbox_style="stamen-terrain")

# Show the figure
st.plotly_chart(fig, use_container_width=True)

Writing streamlit_app.py


In [49]:
from google.colab import files

# Download the file locally
files.download('streamlit_app.py')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [50]:
%%writefile requirements.txt
pandas
streamlit
plotly

Writing requirements.txt


In [51]:
from google.colab import files

# Download the file locally
files.download('requirements.txt')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>